### ISSUE TITLE
v0.0.2

### ISSUE THREAD

**Issue by smilee** [CodeSoom/project-react-2-smilee#8]
이 앱을 언제 사용하나요?
뉴노멀 시대에 데이트 아이디어가 필요할 때 사용합니다.

제약 조건은 무엇인가요?
웹 브라우저가 있어야 하며, 하루에 세 번만 쓸 수 있습니다.

구체적인 사례는 무엇인가요?
연인을 만나기 전에 데이트 아이디어 세개를 얻어, 그 중 하고싶은 것을 고릅니다.

이번주에 구현 할 기능을 우선 순위대로 작성해 주세요.
화면의 뽑기기계를 돌리면 랜덤한 데이트 아이디어를 확인할 수 있습니다. 하루에 세 번만 돌릴 수 있습니다.

**Comment by Kihyun92** [comment]
개인적으로 너무 좋은 서비스같아요 ㅎㅎ 요즘 코로나때문에 여자친구를 만나도 할게없는데 참고 해야겠습니다 👍

**Comment by Kihyun92** [comment]
다음 버전에 대한 작업은 어떻게 진행되고 있는지 궁금합니다~ 😁

**Comment by smilee** [comment]
https://github.com/CodeSoom/project-react-2-smilee/pull/11
